//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Input/ProgressBarInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ProgressBarInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ProgressBarInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ProgressBarInput"",
    ""maps"": [
        {
            ""name"": ""ProgressBar"",
            ""id"": ""ef5a79a1-d7d5-48b8-8b07-4c6441003e14"",
            ""actions"": [
                {
                    ""name"": ""Charge"",
                    ""type"": ""Button"",
                    ""id"": ""ac771b35-e1d5-4bdd-9fac-64d23ec86973"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0b9c2e50-47fb-4568-8347-107bed1de9c5"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Charge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ProgressBar
        m_ProgressBar = asset.FindActionMap("ProgressBar", throwIfNotFound: true);
        m_ProgressBar_Charge = m_ProgressBar.FindAction("Charge", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ProgressBar
    private readonly InputActionMap m_ProgressBar;
    private IProgressBarActions m_ProgressBarActionsCallbackInterface;
    private readonly InputAction m_ProgressBar_Charge;
    public struct ProgressBarActions
    {
        private @ProgressBarInput m_Wrapper;
        public ProgressBarActions(@ProgressBarInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Charge => m_Wrapper.m_ProgressBar_Charge;
        public InputActionMap Get() { return m_Wrapper.m_ProgressBar; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ProgressBarActions set) { return set.Get(); }
        public void SetCallbacks(IProgressBarActions instance)
        {
            if (m_Wrapper.m_ProgressBarActionsCallbackInterface != null)
            {
                @Charge.started -= m_Wrapper.m_ProgressBarActionsCallbackInterface.OnCharge;
                @Charge.performed -= m_Wrapper.m_ProgressBarActionsCallbackInterface.OnCharge;
                @Charge.canceled -= m_Wrapper.m_ProgressBarActionsCallbackInterface.OnCharge;
            }
            m_Wrapper.m_ProgressBarActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Charge.started += instance.OnCharge;
                @Charge.performed += instance.OnCharge;
                @Charge.canceled += instance.OnCharge;
            }
        }
    }
    public ProgressBarActions @ProgressBar => new ProgressBarActions(this);
    public interface IProgressBarActions
    {
        void OnCharge(InputAction.CallbackContext context);
    }
}
